# Inventaire Ansible - CYNA LAB G5
# Remplacer ansible_user=ubuntu par le vrai utilisateur Linux si besoin.

[web]
srv-web-cyna ansible_host=10.0.10.10 ansible_user=ubuntu

[wazuh]
srv-wazuh-cyna ansible_host=10.0.20.20 ansible_user=ubuntu

[linux_targets:children]
web
wazuh

# Windows Server présent dans l'infrastructure, mais non géré ici.
# Pour le gérer avec Ansible, il faudrait WinRM.
[windows]
dc1-cyna ansible_host=10.0.20.10

[linux_targets:vars]
ansible_python_interpreter=/usr/bin/python3
